
#test test hello
['cust', '1_avg_quant', '2_avg_quant']
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def generateKey(groupingAttributes, row):
    output = []
    for thing in groupingAttributes:
        output.append(row[thing])
    return output

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    rows = cur.fetchall()
    
    _global = []
    
    
    mfTable = {}
    groupingAttributes = ['cust']

    
    class Key:
        def __init__(self, cust):
            self.cust = cust

        def __repr__(self):
            attrs = ", ".join(f"{k}={v}" for k, v in self.__dict__.items())
            return f"Key({attrs})"

        def __eq__(self, other):
            return isinstance(other, Key) and self.__dict__ == other.__dict__

        def __hash__(self):
            return hash(tuple(self.__dict__.values()))
    

    
    class Row:
        def __init__(self,_1_avg_quant=0,_2_avg_quant=0):
            self._1_avg_quant = _1_avg_quant
            self._2_avg_quant = _2_avg_quant

            self.sum = 0
            self.count = 0
            self.min = float('inf')
            self.max = float('-inf')

        def __repr__(self):
            attrs = ", ".join(f"{k}={v}" for k, v in self.__dict__.items())
            return f"Row({attrs})"


    mfValue = [0, 0] 
    #int n = 2

    #generate mf table

    for row in rows:
        #key = tuple(generateKey(groupingAttributes, row))
        key = Key(*[row[attr] for attr in ['cust']])
        if key not in mfTable:
            mfTable[key] = Row()
            #print(key)
    #print(mfTable)


    
            
    for key, value in mfTable.items():
        value.sum = 0
        value.count = 0
        value.min = float('inf')
        value.max = float('-inf')
    
    #avg
    for row in rows:
        for key, value in mfTable.items():
            if key.cust == row['cust']: #if row matches key
                if row["state"] == 'NY': #if we satisfy suchThat
                    value.sum += row["quant"] #compute aggregate
                    value.count += 1
                    value._1_avg_quant = value.sum / value.count
                    #return
            
            
    for key, value in mfTable.items():
        value.sum = 0
        value.count = 0
        value.min = float('inf')
        value.max = float('-inf')
    
    #avg
    for row in rows:
        for key, value in mfTable.items():
            if key.cust == row['cust']: #if row matches key
                if row["state"] == 'NJ': #if we satisfy suchThat
                    value.sum += row["quant"] #compute aggregate
                    value.count += 1
                    value._2_avg_quant = value.sum / value.count
                    #return
            
    #having
    theOutput = []
    for key, value in mfTable.items():
        if ['TRUE']:
            theOutput.append((key, value))

    outputFR = []
    for key, value in theOutput:
        theRow = []
        for attr in ['cust', '1_avg_quant', '2_avg_quant']:
            if attr in ['cust']:
                theRow.append(getattr(key, attr))
            else:
                the = "_" + attr
                theRow.append(getattr(value, the))
        outputFR.append(theRow);
    
    
    return tabulate.tabulate(outputFR,
                        headers=['cust', '1_avg_quant', '2_avg_quant'], tablefmt="psql")


def main():
    print(query())

    
if "__main__" == __name__:
    main()
    