
#test test hello
['cust', '1_avg_price', '2_sum_quant', '3_min_quant']
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def generateKey(groupingAttributes, row):
    output = []
    for thing in groupingAttributes:
        output.append(row[thing])
    return output

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    rows = cur.fetchall()
    
    _global = []
    
    
    mfTable = {}
    groupingAttributes = ['cust', 'prod']

    
    class Key:
        def __init__(self, cust, prod):
            self.cust = cust
            self.prod = prod

        def __repr__(self):
            attrs = ", ".join(f"{k}={v}" for k, v in self.__dict__.items())
            return f"Key({attrs})"

        def __eq__(self, other):
            return isinstance(other, Key) and self.__dict__ == other.__dict__

        def __hash__(self):
            return hash(tuple(self.__dict__.values()))
    

    
    class Row:
        def __init__(self,_1_avg_price=None,_2_sum_quant=None,_3_min_quant=None):
            self._1_avg_price = _1_avg_price
            self._2_sum_quant = _2_sum_quant
            self._3_min_quant = _3_min_quant

            self.sum = 0
            self.count = 0
            self.min = float('inf')
            self.max = float('-inf')

        def __repr__(self):
            attrs = ", ".join(f"{k}={v}" for k, v in self.__dict__.items())
            return f"Row({attrs})"


    mfValue = [0, 0, 0]
    #int n = 3

    for row in rows:
        #key = tuple(generateKey(groupingAttributes, row))
        key = Key(*[row[attr] for attr in ['cust', 'prod']])
        if key not in mfTable:
            mfTable[key] = Row()
            #print(key)
    #print(mfTable)


    
            
    for key, value in mfTable.items():
        value.sum = 0
        value.count = 0
        value.min = float('inf')
        value.max = float('-inf')
    
    #avg
    for row in rows:
        for key, value in mfTable.items():
            if key.cust == row['cust'] and key.prod == row['prod']:
                if row["state"]=='CT':
                    value.sum += row["quant"]
                    value.count += 1
                    value._1_avg_price = value.sum / value.count
                    #return
            
            
    for key, value in mfTable.items():
        value.sum = 0
        value.count = 0
        value.min = float('inf')
        value.max = float('-inf')
    
    #sum
    for row in rows:
        for key, value in mfTable.items():
            if key.cust == row['cust'] and key.prod == row['prod']:
                if row["state"]=='NY':
                    value.sum += row["quant"]
                    value._2_sum_quant = value.sum
                    #return
            
            
    for key, value in mfTable.items():
        value.sum = 0
        value.count = 0
        value.min = float('inf')
        value.max = float('-inf')
    
    #min
    for row in rows:
        for key, value in mfTable.items():
            if key.cust == row['cust'] and key.prod == row['prod']:
                if row["state"]=='NJ':
                    value.min = min(value.min, row["quant"])
                    value._3_min_quant = value.min
                    #return
            
    #having
    theOutput = []
    for key, value in mfTable.items():
        if value._2_sum_quant > 100 or value._1_avg_price < 50 and value._3_min_quant >= 5:
            theOutput.append((key, value))

    outputFR = []
    for key, value in theOutput:
        theRow = []
        for attr in ['cust', 'prod', '1_avg_price', '2_sum_quant', '3_min_quant']:
            if attr in ['cust', 'prod']:
                theRow.append(getattr(key, attr))
            else:
                the = "_" + attr
                theRow.append(getattr(value, the))
        outputFR.append(theRow);
    
    
    return tabulate.tabulate(outputFR,
                        headers=['cust', 'prod', '1_avg_price', '2_sum_quant', '3_min_quant'], tablefmt="psql")


def main():
    print(query())
    
if "__main__" == __name__:
    main()
    